### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DoubleDipper** [gagomap/fail2ban_settings#1]
i get this error after settings overwrite:
- Restarting authentication failure monitor fail2ban                                   ERROR  No file(s) found for glob /var/log/mysql/error.log
  ERROR  Failed during configuration: Have not found any log file for mysqld-auth         jail

**Comment by DoubleDipper** [comment]
fix:
sudo mkdir /var/log/mysql/error.log
sudo mkdir /var/www/yourwebsitefolder/htdocs/wp-content/spam.log

**Comment by gagomap** [comment]
No, you must add these following line to file: etc/mysql/conf.d/auth.cnf

``` bash
[mysqld]
log_error = /var/log/mysql/error.log
log-warning = 2
```

:) 

It will enable log file for mysql

And remember change my email in jail.local to your mail. I have seen a lot of mail from your vps send to my inbox.

**Comment by DoubleDipper** [comment]
oh thanks! what about htdocs? I got the same error for htdocs.

**Comment by DoubleDipper** [comment]
And sorry about the emails, where do i change the email? i don't see it.

**Comment by gagomap** [comment]
Your "htdocs error" path is log file for Antispam-bee plugin for wordpress.

If you install Antispam-bee, please add this line to file wp-config.php of your website, before "/\* That's all, stop editing! Happy blogging. */":

``` bash
define('ANTISPAM_BEE_LOG_FILE', 'path/to/file/spam.log');
```

You can find my email admin...@dautu365.com in jail.local

``` bash
destemail =admin...@dautu365.com
dest=admin...@dautu365.com,
```

**Comment by DoubleDipper** [comment]
i think i removed all of your emails :). since it wasn't showing in filezilla i had to just delete and edit a new one. also, i'm still getting this error:  

```
* Restarting authentication failure monitor fail2ban                                ERROR  No file(s) found for glob /var/log/mysql/error.log
ERROR  Failed during configuration: Have not found any log file for mysqld-auth jail

```

i stopped receiving that error after creating /var/log/mysql/error.log. but after your comment i deleted the folder and created and auth.cnf file and put  this in the file: 

```
[mysqld]
log_error = /var/log/mysql/error.log
log-warning = 2

```

**Comment by gagomap** [comment]
You must restart mysql server by command : `service mysql restart` ;)

**Comment by DoubleDipper** [comment]
ahh i think i got it! thank you so much for your help! can i ask you one more thing?  i will stop bothering you afterward, i promise lol. the part where you say to put this in server block: 

```
location = /wp-login.php {
    limit_req   zone=one  burst=1 nodelay;
    include fastcgi_params;
    fastcgi_pass 127.0.0.1:9000;
}
```

i do not see it in  /etc/nginx/nginx.conf
and when i try putting that code anywhere in the file i get a restart fail?

**Comment by gagomap** [comment]
Are you using Easy Engine ? Or nginx on ubuntu ?

it's in /etc/nginx/sites-available/default or /etc/nginx/sites-available/yoursite.com

just add those line in a server block.

**Comment by DoubleDipper** [comment]
i think that worked! i'm not getting an error after putting it in etc/nginx/sites-available/default. thank you so much you've been a great help! i was following that rt tutorial too and nowhere did it mention where i was suppose to go to put that code. maybe it's common knowledge to people who code, but i was painfully stuck at that step lol. you've saved me a lot of time and headaches, thanks again!

**Comment by gagomap** [comment]
No problem :D I'm sorry for my tutorial, because i'm not good at english
Thank you !

**Comment by DoubleDipper** [comment]
i'm no good at english either and it's the only language i speak, so you're doing way better than me ! lol
